### ISSUE TITLE
waveform for an audio file

### ISSUE THREAD

**Issue by Tanisha27** [FlexMonkey/AudioSynthesis#3]
I am trying to display the waveform for an audio file while playing in say, AVAudioPlayer. But I have no idea how I can do it. Right now I am showing the waveform just like siri's waveform. But i want to show variable amplitudes and not the same amplitude for all the cycles like in siri. Please help me!!
I'll be really grateful.

**Comment by FlexMonkey** [comment]
Hi, you should reach out to AudioKit directly for this. You can contact the team via Twitter at https://twitter.com/AudioKitMan
